### ISSUE TITLE
Question: Usage of the ros dmp tool

### ISSUE THREAD

**Issue by matteopantano** [ARQ-CRISP/ros_dmp_tools#1]
Hello,

I am wondering about the usage of the tool. Has it been used wit real robots or simulated ones? Is there a paper describing its functionalities?

Best,
Matteo

**Comment by gokhansolak** [comment]
Hi Matteo,

Sorry for the late answer.

This package is more like a wrapper to run DMPs under ROS. It depends on the DMPBBO library. 

We are using it with both real and simulated robots. You can see the example usage in [gokhansolak /
lfd-experiments-iros2019](https://github.com/gokhansolak/lfd-experiments-iros2019). There is a publication mentioned in that repository, but it is not mainly about this package.

Best,
Gokhan

**Comment by matteopantano** [comment]
Thanks!
